language: php

php:
  - 5.3
  - 5.4
  - 5.5

services:
  - mysql
  - memcached
  - elasticsearch
  - redis-server

before_script:
  - tests/travis/install-php-runkit.sh
  - tests/travis/install-php-svm.sh
  - printf "\n" | pecl install imagick
  - pecl install stats
  - sudo apt-get install libgearman-dev && pecl install gearman
  - sh -c "if [ `php-config --vernum` -ge 50500 ]; then printf "yes\n" | pecl install apcu-beta; fi"
  - phpenv config-add tests/travis/php.ini
  - phpenv config-add tests/travis/php-$TRAVIS_PHP_VERSION.ini

  - composer self-update
  - composer install --dev
  - scripts/cm.php app generate-config-local tests/travis/config.json
  - scripts/cm.php app set-deploy-version

script: phpunit --debug

matrix:
  allow_failures:
    - php: 5.4
    - php: 5.5

notifications:
  email: false
